DROP TABLE IF EXISTS cgan_ustax_ws.saves_cch_003_append_stg1;
CREATE TABLE cgan_ustax_ws.saves_cch_003_append_stg1 as
select distinct base.*

, coalesce(cct.flag_called_intuit, 0) as flag_called_intuit
, coalesce(cct.flag_called_within_7_days, 0) as flag_called_within_7_days 
from cgan_ustax_ws.saves_cch_002_metrics_diydiwm as base
left join cgan_ustax_ws.saves_cch_002_contacts as cct
  on cast(cct.auth_id as string) = cast(base.auth_id as string)
    and cct.tax_year = base.tax_year
    and cct.date_outreach_start_pst = base.date_outreach_start_pst  
    and cct.CSO = base.CSO
    and cct.outreach_channel = base.outreach_channel 
;

DROP TABLE IF EXISTS cgan_ustax_ws.saves_cch_003_append_stg;
CREATE TABLE cgan_ustax_ws.saves_cch_003_append_stg as
select distinct base.*
, coalesce(reauth.flag_reauth, 0) as flag_reauth 
from cgan_ustax_ws.saves_cch_003_append_stg1 as base
left join cgan_ustax_ws.saves_cch_002_reauth as reauth
  on cast(base.auth_id as string) = cast(reauth.auth_id as string)
    and reauth.tax_year = base.tax_year
    and reauth.date_outreach_start_pst = base.date_outreach_start_pst 
    and reauth.CSO = base.CSO
    and reauth.outreach_channel = base.outreach_channel 
;

DROP TABLE IF EXISTS cgan_ustax_ws.saves_cch_003_append_diwm;
CREATE TABLE cgan_ustax_ws.saves_cch_003_append_diwm as
select outreach_channel,
outreach_channel_type,
outreach_channel_subtype,
outreach_campaign_id_primary,
outreach_campaign_name,
outreach_campaign_id_secondary,
timestamp_outreach_start_pst,
date_outreach_start_pst,
outreach_delivered_primary,
outreach_delivered_secondary,
expert_id,
flag_outreach_delivered,
pseudonym_id,
customer_contact_pii_type,
customer_contact_pii_value,
intuit_contact_type,
intuit_contact_value,
recording_id,
outreach_duration_seconds,
outreach_engagement_type_primary,
outreach_opened,
outreach_click,
outreach_engagement_value_primary,
outreach_engagement_type_secondary,
outreach_engagement_value_secondary,
Type,
Driver,
Priority,
Product,
Desired_Outreach_Channel,
Stack_Rank,
Campaign_Name,
Status,
Target_Launch,
Call_to_Action,
Hypothesis,
Size_Number_of_Customers,
Content,
List_Provided_By,
CSO,
Send_Schedule,
USPS_Status,
Next_Steps_Comments,
Link_to_Checklist,
Link_to_Content_Email_Call_Script,
Added_to_IEP_Expert_Outreach_Hub,
Results_Summary,
Results_Link,
Revenue_ROI_Cost_of_Campaign,
Test,
Test_Recipes,
Customer_List_Attributes,
Customer_Cohort,
Refund_Trigger,
Financial_Impact,
Email_Ops_Notes,
Legal,
Reviewed_with_CG_Marketing,
Selected_Outreach_Channel,
Selected_Expert_Profile,
Requestor,
Org,
Slack_Channel,
Kickoff,
Date_of_SR_Incident,
Time_of_SR_Incident_Pacific,
Link_to_Data_JIRA_Attach_CSV,
Created_By,
Created,
timestamp_ingested_utc,
date_outreach_ingested_pst,
auth_id,
tax_pt_date,
tax_year,
season_part,
tax_year_ind,
reporting_date,
tax_week,
tax_day,
flag_tax_year_current,
flag_tax_year_prior,
first_start_date,
first_completed_date,
first_fed_efile_rejected_date,
first_print_to_mail_date,
first_fed_efile_accepted_date,
first_file_success_date,
flag_start,
flag_complete,
flag_reject,
flag_file_success,
tto_segment_rollup,
tto_segment,
customer_type_rollup,
start_sku_rollup,
completed_sku_rollup,
completed_sku,
flag_called_intuit,
flag_called_within_7_days,
flag_reauth 
from  cgan_ustax_ws.saves_cch_003_append_stg -- current year
union 
select outreach_channel,
outreach_channel_type,
outreach_channel_subtype,
outreach_campaign_id_primary,
outreach_campaign_name,
outreach_campaign_id_secondary,
timestamp_outreach_start_pst,
date_outreach_start_pst,
outreach_delivered_primary,
outreach_delivered_secondary,
expert_id,
flag_outreach_delivered,
pseudonym_id,
customer_contact_pii_type,
customer_contact_pii_value,
intuit_contact_type,
intuit_contact_value,
recording_id,
outreach_duration_seconds,
outreach_engagement_type_primary,
outreach_opened,
outreach_click,
outreach_engagement_value_primary,
outreach_engagement_type_secondary,
outreach_engagement_value_secondary,
Type,
Driver,
Priority,
Product,
Desired_Outreach_Channel,
Stack_Rank,
Campaign_Name,
Status,
Target_Launch,
Call_to_Action,
Hypothesis,
Size_Number_of_Customers,
Content,
List_Provided_By,
CSO,
Send_Schedule,
USPS_Status,
Next_Steps_Comments,
Link_to_Checklist,
Link_to_Content_Email_Call_Script,
Added_to_IEP_Expert_Outreach_Hub,
Results_Summary,
Results_Link,
Revenue_ROI_Cost_of_Campaign,
Test,
Test_Recipes,
Customer_List_Attributes,
Customer_Cohort,
Refund_Trigger,
Financial_Impact,
Email_Ops_Notes,
Legal,
Reviewed_with_CG_Marketing,
Selected_Outreach_Channel,
Selected_Expert_Profile,
Requestor,
Org,
Slack_Channel,
Kickoff,
Date_of_SR_Incident,
Time_of_SR_Incident_Pacific,
Link_to_Data_JIRA_Attach_CSV,
Created_By,
Created,
timestamp_ingested_utc,
date_outreach_ingested_pst,
auth_id,
tax_pt_date,
tax_year,
season_part,
tax_year_ind,
reporting_date,
tax_week,
tax_day,
flag_tax_year_current,
flag_tax_year_prior,
first_start_date,
first_completed_date,
first_fed_efile_rejected_date,
first_print_to_mail_date,
first_fed_efile_accepted_date,
first_file_success_date,
flag_start,
flag_complete,
flag_reject,
flag_file_success,
tto_segment_rollup,
tto_segment,
customer_type_rollup,
start_sku_rollup,
completed_sku_rollup,
completed_sku,
flag_called_intuit,
flag_called_within_7_days,
flag_reauth from
 cgan_ustax_ws.saves_cch_003_append_diydiwm_historical --current previous year
;
